config_version: 1

printers:
  - id: gastezimmer-labelprinter-thermopapier-giraffe-zpl
    name: "Gästezimmer Giraffe"
    model: LP 2824 Plus
    vendor: Zebra
    driver: zpl

    connection:
      protocol: raw9100
      host: 192.168.0.101
      port: 9100
      timeout_ms: 3000

    media:
      loaded:
        width_mm: 50
        height_mm: 24
        color: white
        type: thermal

    alignment:
      dpi: 203
      offset_x_mm: 0.0
      offset_y_mm: 0.0

    zpl:
      darkness: 15
      print_speed: 3
      print_mode: tear_off

    defaults:
      copies: 1
      rotation: 0

    capabilities:
      supports_status: true
      supports_graphics: true
      supports_cut: false

    enabled: true
